spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/szxy_evaluation_manage?useUnicode=true&characterEncoding=UTF-8
    username: evaluation
    password: evaluation$123
    driver-class-name: com.mysql.cj.jdbc.Driver
