spring:
  rabbitmq:
    host: 172.16.110.128
    port: 5672
    username: admin
    password: Aa135790
    #channelRpcTimeout: PT30S
    listener:
      # listener容器类型（simple、direct）
      type: simple
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 20
        prefetch: 1
